# Generated by Django 4.0 on 2022-03-30 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goali', '0004_subtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='removed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
